### ISSUE TITLE
npm run dev问题

### ISSUE THREAD

**Issue by ZongDuCha** [lzxb/vue2-demo#18]
最后一步运行的时候出错：
c:\Users\Administrator\Documents\Vue\git\vue2-demo-master>cnpm run dev

vue-demo@1.0.0 dev c:\Users\Administrator\Documents\Vue\git\vue2-demo-master
node server

module.js:538
throw err;
^

Error: Cannot find module 'autoprefixer'
at Function.Module._resolveFilename (module.js:536:15)
at Function.Module._load (module.js:466:25)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object. (c:\Users\Administrator\Documents\Vue\git\vue2-demo-master\webpack.config.js:80:13)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object. (c:\Users\Administrator\Documents\Vue\git\vue2-demo-master\server.js:3:23)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)

安装了autoprefixer也运行不了

**Comment by lzxb** [comment]
晚上我回去看看

**Comment by lzxb** [comment]
我试了一下，没有遇到你说的问题。

**Comment by hammersmith-xie** [comment]
webpack.config.js里地module少了s，应该是modules
