### ISSUE TITLE
error in node 14.5

### ISSUE THREAD

**Issue by nguyenhuutinh** [lzxb/vue2-demo#28]
Hi, I got this error when run on node 14.5
downgrade to 12 working well

please take a look. thanks

```
Error: Module parse failed: Unexpected token (76:21)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       enumerable: false,
|       value: {
>         title: title?.text() || '',
|         meta: meta?.text() || '',
|         link: link?.text() || '',
    at Object../src/entry-server.ts (js/app.js:136:7)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Object../dist/ssr-genesis/src/entry-server.ts (dist/ssr-genesis/src/entry-server.ts:3:15)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Object.0 (js/app.js:147:18)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at js/app.js:85:18
    at Object.<anonymous> (js/app.js:88:10)
    at evaluateModule (/Users/root/MyProjects/nodejs/vue2-demo/node_modules/vue-server-renderer/build.dev.js:9318:21)
    at /Users/root/MyProjects/nodejs/vue2-demo/node_modules/vue-server-renderer/build.dev.js:9376:18
```

**Comment by lzxb** [comment]
I'll see it later

**Comment by lzxb** [comment]
你重新拉一下代码试试。
