### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by lizhoukai** [lzxb/vue2-demo#5]
```js
[HPM] Proxy created: **  ->  https://cnodejs.org/
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at Server.listen (/Users/kevinli/Desktop/vue2-demo/node_modules/.npminstall/webpack-dev-server/1.16.2/webpack-dev-server/lib/Server.js:324:27)
    at Object.<anonymous> (/Users/kevinli/Desktop/vue2-demo/server.js:20:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
```
代理没成功 不知道啥原因

**Comment by lzxb** [comment]
是你本地的3000端口被占用了

**Comment by lizhoukai** [comment]
thx 这低级错误。。。😊

**Comment by lzxb** [comment]
。。。
